require 'xcodeproj'
require 'plist'

require_relative 'ambient/project_helper'
require_relative 'ambient/capabilities_helper'
require_relative 'ambient/plist_helper'
require_relative 'ambient/dsl'
require_relative 'ambient/project_creation'
require_relative 'ambient/init'
require_relative 'ambient/application'
